spring.application.name=ms-inscripciones
server.port=${SERVER_PORT:8082}

spring.datasource.url=jdbc:oracle:thin:@${ORACLE_TNS_ALIAS:plataformacursos_high}?TNS_ADMIN=${TNS_ADMIN:src/main/resources/wallet}
spring.datasource.username=${ORACLE_DB_USER:ADMIN}
spring.datasource.password=${ORACLE_DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
